#!/usr/bin/env python3

from lexer import lex
from parser import (Parser, CallStatementNode, UnaryOperationNode, ListLiteralNode)
from evaluator import (Evaluator, SpreadArgs)
from analyzer import Analyzer
from chestnut_types import (ChestnutString, ChestnutInteger, ChestnutBoolean, ChestnutFloat, ChestnutNull, ChestnutList)
from token_types import(Token, TokenType)

import sys

if __name__ == "__main__":
    file = sys.argv[1] if ".nuts" in sys.argv[1] else None
    args = sys.argv[2:]
    if file:
        with open(file) as hello:
            # Lexing
            tokens = lex("".join(hello.readlines()), file)

            # Parsing
            parser = Parser(tokens)
            ast = parser.parse_program()

            # Semantic analysis
            analyzer = Analyzer()
            for node in ast:
                analyzer.analyze(node)

            # Evaluation.
            evaluator = Evaluator()
            for node in ast:
                evaluator.evaluate(node)

            # If we had a main function defined, execute it.
            argtokens = []
            for x in args:
                t = Token("Placeholder", x, 0, 0)
                if len(argtokens) > 0:
                    argtokens.append(Token("Comma", ",", 0, 0))

                if x == "false" or x == "true":
                    t.label = "Boolean"
                    t.data = ChestnutBoolean(t.data == "true")
                    argtokens.append(t)
                elif x == "null":
                    t.label = "Null"
                    t.data = ChestnutNull(None)
                    argtokens.append(t)
                elif x.isnumeric():
                    t.label = "Integer"
                    t.data = ChestnutInteger(int(t.data))
                    argtokens.append(t)
                else:
                    try:
                        fval = float(t.data)
                        t.label = "Float"
                        t.data = ChestnutFloat(fval)
                        argtokens.append(t)
                    except:
                        t.label = "String"
                        t.data = ChestnutString(t.data)
                        argtokens.append(t)

            main_scope = evaluator.find_first_scope_containing("main")
            has_main = "main" in evaluator.function_register.functions
            if has_main:
                identifier = Token("Identifier", "main", 0, 1, "<interpreter>")
                lparen = Token("LParen", "(", 0, 5, "<interpreter>")
                rparen = Token("RParen", ")", 0, 6, "<interpreter>")
                tokens = [identifier, lparen]
                tokens.extend(argtokens)
                tokens.append(rparen)
                p = Parser(tokens, 1)
                expr = p.parse_expression()
                evaluator.evaluate(expr)
            else:
                print("No main function defined.")
    else:
        print("Nothing to evaluate")
